### ISSUE TITLE
Error loading script: img23D.py

### ISSUE THREAD

**Issue by CrashHoshiBits** [AlbedoFire/sd-webui-triposr#2]
i used all the upgrade and install commands
pip install git+https://github.com/tatsy/torchmcubes.git
pip install --upgrade setuptools

and i ge this problem

*** Error loading script: img23D.py
    Traceback (most recent call last):
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\scripts\img23D.py", line 4, in <module>
        from tsr.utils import preprocess
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\__init__.py", line 5, in <module>
        from .system import TSR
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\system.py", line 8, in <module>
        import trimesh
    ModuleNotFoundError: No module named 'trimesh'

---
*** Error loading script: ui_tab.py
    Traceback (most recent call last):
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\scripts\ui_tab.py", line 3, in <module>
        from tsr.utils import preprocess
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\__init__.py", line 5, in <module>
        from .system import TSR
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\system.py", line 8, in <module>
        import trimesh
    ModuleNotFoundError: No module named 'trimesh'

**Comment by angleyanalbedo** [comment]
you need to install trimesh

**Comment by CrashHoshiBits** [comment]
I installed trimesh with pip install trimesh[all] 
nothing changed, is there another thing i need to install?
im a newbie in this things


venv "C:\Users\Roritamashi\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.9.3
Commit hash: 1c0a0c4c26f78c32095ebc7f8af82f5c04fca8c0
*** Error running install.py for extension C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr.
*** Command: "C:\Users\Roritamashi\stable-diffusion-webui\venv\Scripts\python.exe" "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\install.py"
*** Error code: 1
*** stdout: Installing requirements for torchmcubes
***
*** stderr: Traceback (most recent call last):
***   File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\install.py", line 4, in <module>
***     launch.run_pip("install git+https://github.com/tatsy/torchmcubes.git", "requirements for torchmcubes")
***   File "C:\Users\Roritamashi\stable-diffusion-webui\modules\launch_utils.py", line 143, in run_pip
***     return run(f'"{python}" -m pip {command} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}", live=live)
***   File "C:\Users\Roritamashi\stable-diffusion-webui\modules\launch_utils.py", line 115, in run
***     raise RuntimeError("\n".join(error_bits))
*** RuntimeError: Couldn't install requirements for torchmcubes.
*** Command: "C:\Users\Roritamashi\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/tatsy/torchmcubes.git --prefer-binary
*** Error code: 1
*** stdout: Collecting git+https://github.com/tatsy/torchmcubes.git
***   Cloning https://github.com/tatsy/torchmcubes.git to c:\users\roritamashi\appdata\local\temp\pip-req-build-hr_kuexb***   Resolved https://github.com/tatsy/torchmcubes.git to commit 3aef8afa5f21b113afc4f4ea148baee850cbd472
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'error'
***
*** stderr:   Running command git clone --filter=blob:none --quiet https://github.com/tatsy/torchmcubes.git 'C:\Users\Roritamashi\AppData\Local\Temp\pip-req-build-hr_kuexb'
***   error: subprocess-exited-with-error
***
***   Getting requirements to build wheel did not run successfully.
***   exit code: 1
***
***   [17 lines of output]
***   Traceback (most recent call last):
***     File "C:\Users\Roritamashi\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
***       main()
***     File "C:\Users\Roritamashi\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
***       json_out['return_val'] = hook(**hook_input['kwargs'])
***     File "C:\Users\Roritamashi\stable-diffusion-webui\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
***       return hook(config_settings)
***     File "C:\Users\Roritamashi\AppData\Local\Temp\pip-build-env-qxlbzgqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
***       return self._get_build_requires(config_settings, requirements=['wheel'])
***     File "C:\Users\Roritamashi\AppData\Local\Temp\pip-build-env-qxlbzgqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
***       self.run_setup()
***     File "C:\Users\Roritamashi\AppData\Local\Temp\pip-build-env-qxlbzgqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
***       super().run_setup(setup_script=setup_script)
***     File "C:\Users\Roritamashi\AppData\Local\Temp\pip-build-env-qxlbzgqn\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
***       exec(code, locals())
***     File "<string>", line 2, in <module>
***   ModuleNotFoundError: No module named 'torch'
***   [end of output]
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
*** error: subprocess-exited-with-error
***
*** Getting requirements to build wheel did not run successfully.
*** exit code: 1
***
*** See above for output.
***
*** note: This error originates from a subprocess, and is likely not a problem with pip.
***
Launching Web UI with arguments: --disable-safe-unpickle
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: img23D.py
    Traceback (most recent call last):
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\scripts\img23D.py", line 4, in <module>
        from tsr.utils import preprocess
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\__init__.py", line 5, in <module>
        from .system import TSR
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\system.py", line 8, in <module>
        import trimesh
    ModuleNotFoundError: No module named 'trimesh'

---
*** Error loading script: ui_tab.py
    Traceback (most recent call last):
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\scripts.py", line 508, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\Roritamashi\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\scripts\ui_tab.py", line 3, in <module>
        from tsr.utils import preprocess
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\__init__.py", line 5, in <module>
        from .system import TSR
      File "C:\Users\Roritamashi\stable-diffusion-webui\extensions\sd-webui-triposr\tsr\system.py", line 8, in <module>
        import trimesh
    ModuleNotFoundError: No module named 'trimesh'

**Comment by angleyanalbedo** [comment]
`torchmcubes` need complied with cuda support， you can not install `torchmcubes` ，because you computer can not complied `torchmcubes` 
- The locally-installed CUDA major version matches the PyTorch-shipped CUDA major version. For example if you have CUDA 11.x installed, make sure to install PyTorch compiled with CUDA 11.x.
-  `setuptools>=49.6.0.` If not, upgrade by `pip install --upgrade setuptools.`
Acorrding to [Triposr](https://github.com/VAST-AI-Research/TripoSR/blob/main/README.md#troubleshooting)

**Comment by angleyanalbedo** [comment]
`ModuleNotFoundError: No module named 'trimesh'` this problem may cause by `install.py` not run successfly because the `torchmcubes` so the `trimesh` do not insalled.  
you can active the webui venv try install trimesh and torchmcubes cpu version 
- `pip install trimesh` and `pip install torchmcubes` but with cpu version it may casu problem according to Triposr
